debian/tmp/usr/bin/compiz*
debian/tmp/usr/lib/libcompiz_core.so.*
debian/tmp/usr/share/compiz/*.png
debian/tmp/usr/share/compiz/core.xml
debian/source_compiz.py usr/share/apport/package-hooks
debian/tmp/usr/share/locale
debian/tmp/usr/share/applications/compiz.desktop
debian/tmp/usr/bin/ccsm
debian/tmp/usr/share/applications/ccsm.desktop
debian/tmp/usr/share/icons/hicolor/*/apps/ccsm.*
debian/tmp/usr/lib/python*/*/ccm*
debian/tmp/usr/lib/python2.7/dist-packages/ccsm*
debian/tmp/usr/share/ccsm
